//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThoiKhoaBieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCTDT
    {
        public int maChiTiet { get; set; }
        public Nullable<int> maHP { get; set; }
        public Nullable<int> maCTDT { get; set; }
    
        public virtual CTDT CTDT { get; set; }
        public virtual HocPhan HocPhan { get; set; }
    }
}
