//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThoiKhoaBieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTDT()
        {
            this.ChiTietCTDTs = new HashSet<ChiTietCTDT>();
        }
    
        public int maCTDT { get; set; }
        public string tenCTDT { get; set; }
        public string tgianDT { get; set; }
        public Nullable<System.DateTime> ngayKy { get; set; }
        public Nullable<int> maNganh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCTDT> ChiTietCTDTs { get; set; }
        public virtual Nganh Nganh { get; set; }
    }
}
