//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThoiKhoaBieu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ScheduleManagementEntities : DbContext
    {
        public ScheduleManagementEntities()
            : base("name=ScheduleManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietCTDT> ChiTietCTDTs { get; set; }
        public virtual DbSet<CTDT> CTDTs { get; set; }
        public virtual DbSet<DangKy> DangKies { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocKy_NienKhoa> HocKy_NienKhoa { get; set; }
        public virtual DbSet<HocPhan> HocPhans { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop_QL> Lop_QL { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<sp_danhSachChiTietCTDT_Result> sp_danhSachChiTietCTDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachChiTietCTDT_Result>("sp_danhSachChiTietCTDT");
        }
    
        public virtual ObjectResult<sp_danhSachCTDT_Result> sp_danhSachCTDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachCTDT_Result>("sp_danhSachCTDT");
        }
    
        public virtual ObjectResult<sp_danhSachDangKy_Result> sp_danhSachDangKy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachDangKy_Result>("sp_danhSachDangKy");
        }
    
        public virtual ObjectResult<sp_danhSachGiangVien_Result> sp_danhSachGiangVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachGiangVien_Result>("sp_danhSachGiangVien");
        }
    
        public virtual ObjectResult<sp_danhSachHocKy_Result> sp_danhSachHocKy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachHocKy_Result>("sp_danhSachHocKy");
        }
    
        public virtual ObjectResult<sp_danhSachHocPhan_Result> sp_danhSachHocPhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachHocPhan_Result>("sp_danhSachHocPhan");
        }
    
        public virtual ObjectResult<sp_danhSachLopQuanLy_Result> sp_danhSachLopQuanLy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachLopQuanLy_Result>("sp_danhSachLopQuanLy");
        }
    
        public virtual ObjectResult<sp_danhSachNganh_Result> sp_danhSachNganh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachNganh_Result>("sp_danhSachNganh");
        }
    
        public virtual ObjectResult<sp_danhSachPCGD_Result> sp_danhSachPCGD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachPCGD_Result>("sp_danhSachPCGD");
        }
    
        public virtual ObjectResult<sp_danhSachPhong_Result> sp_danhSachPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachPhong_Result>("sp_danhSachPhong");
        }
    
        public virtual ObjectResult<sp_danhSachSinhVien_Result> sp_danhSachSinhVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachSinhVien_Result>("sp_danhSachSinhVien");
        }
    
        public virtual ObjectResult<sp_danhSanhKhoa_Result> sp_danhSanhKhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSanhKhoa_Result>("sp_danhSanhKhoa");
        }
    
        public virtual int sp_suaChiTietCTDT(Nullable<int> maChiTiet, Nullable<int> maHp, Nullable<int> maCTDT)
        {
            var maChiTietParameter = maChiTiet.HasValue ?
                new ObjectParameter("maChiTiet", maChiTiet) :
                new ObjectParameter("maChiTiet", typeof(int));
    
            var maHpParameter = maHp.HasValue ?
                new ObjectParameter("maHp", maHp) :
                new ObjectParameter("maHp", typeof(int));
    
            var maCTDTParameter = maCTDT.HasValue ?
                new ObjectParameter("maCTDT", maCTDT) :
                new ObjectParameter("maCTDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaChiTietCTDT", maChiTietParameter, maHpParameter, maCTDTParameter);
        }
    
        public virtual int sp_suaCTDT(Nullable<int> maCTDT, string tenCTDT, string tgianDT, Nullable<System.DateTime> ngayKy, Nullable<int> maNganh)
        {
            var maCTDTParameter = maCTDT.HasValue ?
                new ObjectParameter("maCTDT", maCTDT) :
                new ObjectParameter("maCTDT", typeof(int));
    
            var tenCTDTParameter = tenCTDT != null ?
                new ObjectParameter("tenCTDT", tenCTDT) :
                new ObjectParameter("tenCTDT", typeof(string));
    
            var tgianDTParameter = tgianDT != null ?
                new ObjectParameter("tgianDT", tgianDT) :
                new ObjectParameter("tgianDT", typeof(string));
    
            var ngayKyParameter = ngayKy.HasValue ?
                new ObjectParameter("ngayKy", ngayKy) :
                new ObjectParameter("ngayKy", typeof(System.DateTime));
    
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaCTDT", maCTDTParameter, tenCTDTParameter, tgianDTParameter, ngayKyParameter, maNganhParameter);
        }
    
        public virtual int sp_suaDangKy(Nullable<int> maDangKy, Nullable<int> maPCGD, Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK)
        {
            var maDangKyParameter = maDangKy.HasValue ?
                new ObjectParameter("maDangKy", maDangKy) :
                new ObjectParameter("maDangKy", typeof(int));
    
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaDangKy", maDangKyParameter, maPCGDParameter, maHPParameter, maGVParameter, maHKParameter);
        }
    
        public virtual int sp_suaGiangVien(Nullable<int> maGV, string tenGV, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string email, string dienThoai)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("tenGV", tenGV) :
                new ObjectParameter("tenGV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(bool));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("dienThoai", dienThoai) :
                new ObjectParameter("dienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaGiangVien", maGVParameter, tenGVParameter, ngaySinhParameter, gioiTinhParameter, emailParameter, dienThoaiParameter);
        }
    
        public virtual int sp_suaHocKy(Nullable<int> maHK, string hocKy, string nienKhoa)
        {
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            var hocKyParameter = hocKy != null ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(string));
    
            var nienKhoaParameter = nienKhoa != null ?
                new ObjectParameter("nienKhoa", nienKhoa) :
                new ObjectParameter("nienKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaHocKy", maHKParameter, hocKyParameter, nienKhoaParameter);
        }
    
        public virtual int sp_suaHocPhan(Nullable<int> maHP, string tenHP, Nullable<int> soTinChi)
        {
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var tenHPParameter = tenHP != null ?
                new ObjectParameter("tenHP", tenHP) :
                new ObjectParameter("tenHP", typeof(string));
    
            var soTinChiParameter = soTinChi.HasValue ?
                new ObjectParameter("soTinChi", soTinChi) :
                new ObjectParameter("soTinChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaHocPhan", maHPParameter, tenHPParameter, soTinChiParameter);
        }
    
        public virtual int sp_suaKhoa(Nullable<int> maKhoa, string tenKhoa)
        {
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(int));
    
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("tenKhoa", tenKhoa) :
                new ObjectParameter("tenKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaKhoa", maKhoaParameter, tenKhoaParameter);
        }
    
        public virtual int sp_suaLopQuanLy(Nullable<int> maLop, string tenLop, Nullable<int> maNganh)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(int));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("tenLop", tenLop) :
                new ObjectParameter("tenLop", typeof(string));
    
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaLopQuanLy", maLopParameter, tenLopParameter, maNganhParameter);
        }
    
        public virtual int sp_suaNganh(Nullable<int> maNganh, string tenNganh, Nullable<int> maKhoa)
        {
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            var tenNganhParameter = tenNganh != null ?
                new ObjectParameter("tenNganh", tenNganh) :
                new ObjectParameter("tenNganh", typeof(string));
    
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaNganh", maNganhParameter, tenNganhParameter, maKhoaParameter);
        }
    
        public virtual int sp_suaPCGD(Nullable<int> maPCGD, Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK)
        {
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaPCGD", maPCGDParameter, maHPParameter, maGVParameter, maHKParameter);
        }
    
        public virtual int sp_suaPhong(Nullable<int> maPhong, string tenPhong)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaPhong", maPhongParameter, tenPhongParameter);
        }
    
        public virtual int sp_themChiTietCTDT(Nullable<int> maHp, Nullable<int> maCTDT)
        {
            var maHpParameter = maHp.HasValue ?
                new ObjectParameter("maHp", maHp) :
                new ObjectParameter("maHp", typeof(int));
    
            var maCTDTParameter = maCTDT.HasValue ?
                new ObjectParameter("maCTDT", maCTDT) :
                new ObjectParameter("maCTDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themChiTietCTDT", maHpParameter, maCTDTParameter);
        }
    
        public virtual int sp_themCTDT(string tenCTDT, string tgianDT, Nullable<System.DateTime> ngayKy, Nullable<int> maNganh)
        {
            var tenCTDTParameter = tenCTDT != null ?
                new ObjectParameter("tenCTDT", tenCTDT) :
                new ObjectParameter("tenCTDT", typeof(string));
    
            var tgianDTParameter = tgianDT != null ?
                new ObjectParameter("tgianDT", tgianDT) :
                new ObjectParameter("tgianDT", typeof(string));
    
            var ngayKyParameter = ngayKy.HasValue ?
                new ObjectParameter("ngayKy", ngayKy) :
                new ObjectParameter("ngayKy", typeof(System.DateTime));
    
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themCTDT", tenCTDTParameter, tgianDTParameter, ngayKyParameter, maNganhParameter);
        }
    
        public virtual int sp_themDangKy(Nullable<int> maPCGD, Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK)
        {
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themDangKy", maPCGDParameter, maHPParameter, maGVParameter, maHKParameter);
        }
    
        public virtual int sp_themGiangVien(string tenGV, Nullable<System.DateTime> ngaySinh, Nullable<bool> gioiTinh, string email, string dienThoai)
        {
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("tenGV", tenGV) :
                new ObjectParameter("tenGV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(bool));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("dienThoai", dienThoai) :
                new ObjectParameter("dienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themGiangVien", tenGVParameter, ngaySinhParameter, gioiTinhParameter, emailParameter, dienThoaiParameter);
        }
    
        public virtual int sp_themHocKy(string hocKy, string nienKhoa)
        {
            var hocKyParameter = hocKy != null ?
                new ObjectParameter("hocKy", hocKy) :
                new ObjectParameter("hocKy", typeof(string));
    
            var nienKhoaParameter = nienKhoa != null ?
                new ObjectParameter("nienKhoa", nienKhoa) :
                new ObjectParameter("nienKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themHocKy", hocKyParameter, nienKhoaParameter);
        }
    
        public virtual int sp_themHocPhan(string tenHP, Nullable<int> soTinChi)
        {
            var tenHPParameter = tenHP != null ?
                new ObjectParameter("tenHP", tenHP) :
                new ObjectParameter("tenHP", typeof(string));
    
            var soTinChiParameter = soTinChi.HasValue ?
                new ObjectParameter("soTinChi", soTinChi) :
                new ObjectParameter("soTinChi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themHocPhan", tenHPParameter, soTinChiParameter);
        }
    
        public virtual int sp_themKhoa(string tenKhoa)
        {
            var tenKhoaParameter = tenKhoa != null ?
                new ObjectParameter("tenKhoa", tenKhoa) :
                new ObjectParameter("tenKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themKhoa", tenKhoaParameter);
        }
    
        public virtual int sp_themLopQuanLy(string tenLop, Nullable<int> maNganh)
        {
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("tenLop", tenLop) :
                new ObjectParameter("tenLop", typeof(string));
    
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themLopQuanLy", tenLopParameter, maNganhParameter);
        }
    
        public virtual int sp_themNganh(string tenNganh, Nullable<int> maKhoa)
        {
            var tenNganhParameter = tenNganh != null ?
                new ObjectParameter("tenNganh", tenNganh) :
                new ObjectParameter("tenNganh", typeof(string));
    
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themNganh", tenNganhParameter, maKhoaParameter);
        }
    
        public virtual int sp_themPCGD(Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK)
        {
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themPCGD", maHPParameter, maGVParameter, maHKParameter);
        }
    
        public virtual int sp_themPhong(string tenPhong)
        {
            var tenPhongParameter = tenPhong != null ?
                new ObjectParameter("tenPhong", tenPhong) :
                new ObjectParameter("tenPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themPhong", tenPhongParameter);
        }
    
        public virtual int sp_xoaChiTietCTDT(Nullable<int> maChiTiet)
        {
            var maChiTietParameter = maChiTiet.HasValue ?
                new ObjectParameter("maChiTiet", maChiTiet) :
                new ObjectParameter("maChiTiet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaChiTietCTDT", maChiTietParameter);
        }
    
        public virtual int sp_xoaCTDT(Nullable<int> maCTDT)
        {
            var maCTDTParameter = maCTDT.HasValue ?
                new ObjectParameter("maCTDT", maCTDT) :
                new ObjectParameter("maCTDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaCTDT", maCTDTParameter);
        }
    
        public virtual int sp_xoaDangKy(Nullable<int> maDangKy)
        {
            var maDangKyParameter = maDangKy.HasValue ?
                new ObjectParameter("maDangKy", maDangKy) :
                new ObjectParameter("maDangKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaDangKy", maDangKyParameter);
        }
    
        public virtual int sp_xoaGiangVien(Nullable<int> maGV)
        {
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaGiangVien", maGVParameter);
        }
    
        public virtual int sp_xoaHocKy(Nullable<int> maHK)
        {
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaHocKy", maHKParameter);
        }
    
        public virtual int sp_xoaHocPhan(Nullable<int> maHP)
        {
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaHocPhan", maHPParameter);
        }
    
        public virtual int sp_xoaKhoa(Nullable<int> maKhoa)
        {
            var maKhoaParameter = maKhoa.HasValue ?
                new ObjectParameter("maKhoa", maKhoa) :
                new ObjectParameter("maKhoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaKhoa", maKhoaParameter);
        }
    
        public virtual int sp_xoaLopQuanLy(Nullable<int> maLop)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaLopQuanLy", maLopParameter);
        }
    
        public virtual int sp_xoaNganh(Nullable<int> maNganh)
        {
            var maNganhParameter = maNganh.HasValue ?
                new ObjectParameter("maNganh", maNganh) :
                new ObjectParameter("maNganh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaNganh", maNganhParameter);
        }
    
        public virtual int sp_xoaPCGD(Nullable<int> maPCGD)
        {
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaPCGD", maPCGDParameter);
        }
    
        public virtual int sp_xoaPhong(Nullable<int> maPhong)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaPhong", maPhongParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_danhSachTKB_Result> sp_danhSachTKB(Nullable<int> maSV)
        {
            var maSVParameter = maSV.HasValue ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachTKB_Result>("sp_danhSachTKB", maSVParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_suaThoiKHoaBieu(Nullable<int> maTKB, string thu, Nullable<int> tiet, Nullable<int> maPhong, Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK, Nullable<int> maPCGD, Nullable<int> maLop)
        {
            var maTKBParameter = maTKB.HasValue ?
                new ObjectParameter("maTKB", maTKB) :
                new ObjectParameter("maTKB", typeof(int));
    
            var thuParameter = thu != null ?
                new ObjectParameter("thu", thu) :
                new ObjectParameter("thu", typeof(string));
    
            var tietParameter = tiet.HasValue ?
                new ObjectParameter("tiet", tiet) :
                new ObjectParameter("tiet", typeof(int));
    
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_suaThoiKHoaBieu", maTKBParameter, thuParameter, tietParameter, maPhongParameter, maHPParameter, maGVParameter, maHKParameter, maPCGDParameter, maLopParameter);
        }
    
        public virtual int sp_themThoiKHoaBieu(string thu, Nullable<int> tiet, Nullable<int> maPhong, Nullable<int> maHP, Nullable<int> maGV, Nullable<int> maHK, Nullable<int> maPCGD, Nullable<int> maLop)
        {
            var thuParameter = thu != null ?
                new ObjectParameter("thu", thu) :
                new ObjectParameter("thu", typeof(string));
    
            var tietParameter = tiet.HasValue ?
                new ObjectParameter("tiet", tiet) :
                new ObjectParameter("tiet", typeof(int));
    
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            var maHPParameter = maHP.HasValue ?
                new ObjectParameter("maHP", maHP) :
                new ObjectParameter("maHP", typeof(int));
    
            var maGVParameter = maGV.HasValue ?
                new ObjectParameter("maGV", maGV) :
                new ObjectParameter("maGV", typeof(int));
    
            var maHKParameter = maHK.HasValue ?
                new ObjectParameter("maHK", maHK) :
                new ObjectParameter("maHK", typeof(int));
    
            var maPCGDParameter = maPCGD.HasValue ?
                new ObjectParameter("maPCGD", maPCGD) :
                new ObjectParameter("maPCGD", typeof(int));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("maLop", maLop) :
                new ObjectParameter("maLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themThoiKHoaBieu", thuParameter, tietParameter, maPhongParameter, maHPParameter, maGVParameter, maHKParameter, maPCGDParameter, maLopParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_xoaThoiKhoaBieu(Nullable<int> maTKB)
        {
            var maTKBParameter = maTKB.HasValue ?
                new ObjectParameter("maTKB", maTKB) :
                new ObjectParameter("maTKB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaThoiKhoaBieu", maTKBParameter);
        }
    
        public virtual ObjectResult<sp_danhSachGiangVienFix_Result> sp_danhSachGiangVienFix()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachGiangVienFix_Result>("sp_danhSachGiangVienFix");
        }
    
        public virtual ObjectResult<sp_danhSachGiangVienFixSecond_Result> sp_danhSachGiangVienFixSecond()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_danhSachGiangVienFixSecond_Result>("sp_danhSachGiangVienFixSecond");
        }
    
        public virtual int sp_themGiangVienTest(string tenGV, Nullable<bool> gioiTinh, string email, string dienThoai)
        {
            var tenGVParameter = tenGV != null ?
                new ObjectParameter("tenGV", tenGV) :
                new ObjectParameter("tenGV", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(bool));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("dienThoai", dienThoai) :
                new ObjectParameter("dienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themGiangVienTest", tenGVParameter, gioiTinhParameter, emailParameter, dienThoaiParameter);
        }
    
        public virtual ObjectResult<sp_getGiangVien4CB_Result> sp_getGiangVien4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getGiangVien4CB_Result>("sp_getGiangVien4CB");
        }
    
        public virtual ObjectResult<sp_getHocKy4CB_Result> sp_getHocKy4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getHocKy4CB_Result>("sp_getHocKy4CB");
        }
    
        public virtual ObjectResult<sp_getHocPhan4CB_Result> sp_getHocPhan4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getHocPhan4CB_Result>("sp_getHocPhan4CB");
        }
    
        public virtual ObjectResult<sp_getPCGD4CB_Result> sp_getPCGD4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPCGD4CB_Result>("sp_getPCGD4CB");
        }
    
        public virtual ObjectResult<sp_getKhoa4CB_Result> sp_getKhoa4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getKhoa4CB_Result>("sp_getKhoa4CB");
        }
    
        public virtual ObjectResult<sp_getNganh4CB_Result> sp_getNganh4CB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getNganh4CB_Result>("sp_getNganh4CB");
        }
    }
}
