//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThoiKhoaBieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int maSV { get; set; }
        public string tenSV { get; set; }
        public Nullable<int> maLop { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string diaChi { get; set; }
        public string email { get; set; }
        public string dienThoai { get; set; }
        public Nullable<int> maDangKy { get; set; }
        public Nullable<int> maHP { get; set; }
        public Nullable<int> maHK { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
    
        public virtual DangKy DangKy { get; set; }
        public virtual HocKy_NienKhoa HocKy_NienKhoa { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual Lop_QL Lop_QL { get; set; }
    }
}
