//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThoiKhoaBieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int maTKB { get; set; }
        public string thu { get; set; }
        public Nullable<int> tiet { get; set; }
        public Nullable<int> maPhong { get; set; }
        public Nullable<int> maHP { get; set; }
        public Nullable<int> maGV { get; set; }
        public Nullable<int> maHK { get; set; }
        public Nullable<int> maPCGD { get; set; }
        public Nullable<int> maLop { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKy_NienKhoa HocKy_NienKhoa { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual PhanCongGiangDay PhanCongGiangDay { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual Lop_QL Lop_QL { get; set; }
    }
}
